const USERS_REQUESTED = 'all/USERS_REQUESTED';
const USERS_RECEIVED = 'all/USERS_RECEIVED';
const USERS_ERROR = 'all/USERS_ERROR';

const USERS_COUNT_REQUESTED = 'all/COUNT_REQUESTED';
const USERS_COUNT_RECEIVED = 'all/USERS_COUNT_RECEIVED';
const USERS_COUNT_ERROR = 'all/USERS_COUNT_ERROR';

const SOME_USERS_REQUESTED = 'all/SOME_USERS_REQUESTED';
const SOME_USERS_RECEIVED = 'all/SOME_USERS_RECEIVED';
const SOME_USERS_ERROR = 'all/SOME_USERS_ERROR';

 

	 

const Actions = {
    USERS_REQUESTED,
    USERS_RECEIVED,
    USERS_ERROR,
    USERS_COUNT_REQUESTED,
    USERS_COUNT_RECEIVED,
    USERS_COUNT_ERROR,
    SOME_USERS_REQUESTED,
    SOME_USERS_RECEIVED,
    SOME_USERS_ERROR

};

export default Actions;